# Non-Mod-Specific Properties
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/ShadowGry/emerald-tools/issues"

# Mod Properties
[[mods]]
	modId = "${mod_id}"
	version = "${mod_version}"
	displayName = "${mod_name}"
	updateJSONURL = "https://raw.githubusercontent.com/ShadowGry/emerald-tools/HEAD/update.json"
	displayURL = "https://github.com/ShadowGry/emerald-tools"
	# logoFile = ""
	credits = "TechnoVision"
	authors = "${mod_authors}"
	description = "${mod_description}"

# Dependency Configurations
[[dependencies.${mod_id}]]
	modId = "forge"
	mandatory = true
	versionRange = "${forge_version_range}"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.${mod_id}]]
	modId = "minecraft"
	mandatory = true
	versionRange = "${minecraft_version_range}"
	ordering = "NONE"
	side = "BOTH"
